"""Puertos de persistencia (seccion 4 y 10 del doc de arquitectura:
`ProjectRepository`, `AssetStorePort`). Un solo Protocol grande para las
fases 0-1 -- se separa en varios repositorios de agregado si el dominio
crece lo suficiente como para justificarlo; no antes."""
from __future__ import annotations

from typing import Protocol

from app.domain.story.entities import (
    Asset,
    Canon,
    Chapter,
    Character,
    Location,
    Project,
    Shot,
    Voice,
    VoicePoolVoice,
)


class ProjectRepositoryPort(Protocol):
    def save_project(self, project: Project) -> None: ...
    def get_project(self, project_id: str) -> Project | None: ...
    def get_project_by_slug(self, slug: str) -> Project | None: ...
    def list_projects(self) -> list[Project]: ...

    def save_canon(self, canon: Canon) -> None: ...
    def get_canon(self, project_id: str) -> Canon | None: ...

    def save_chapter(self, chapter: Chapter) -> None: ...
    def list_chapters(self, project_id: str) -> list[Chapter]: ...
    def get_chapter(self, chapter_id: str) -> Chapter | None: ...

    def replace_shots(self, chapter_id: str, shots: list[Shot]) -> None: ...
    def list_shots(self, chapter_id: str) -> list[Shot]: ...
    def get_shot(self, shot_id: str) -> Shot | None: ...
    def save_shot(self, shot: Shot) -> None: ...
    def delete_shot(self, shot_id: str) -> None: ...

    def save_character(self, character: Character) -> None: ...
    def list_characters(self, project_id: str) -> list[Character]: ...
    def get_character(self, character_id: str) -> Character | None: ...
    def get_character_by_slug(self, project_id: str, slug: str) -> Character | None: ...

    def save_location(self, location: Location) -> None: ...
    def list_locations(self, project_id: str) -> list[Location]: ...
    def get_location(self, location_id: str) -> Location | None: ...
    def get_location_by_slug(self, project_id: str, slug: str) -> Location | None: ...

    def save_voice(self, voice: Voice) -> None: ...
    def list_voices(self, project_id: str) -> list[Voice]: ...

    def replace_scanned_assets(self, project_id: str, chapter_id: str, assets: list[Asset]) -> None: ...
    def save_asset(self, asset: Asset) -> None: ...
    def list_assets(self, project_id: str, chapter_id: str | None = None) -> list[Asset]: ...

    # -- Pool de voces a nivel canal (no por proyecto) -----------------------
    def save_pool_voice(self, voice: VoicePoolVoice) -> None: ...
    def list_pool_voices(self) -> list[VoicePoolVoice]: ...
    def get_pool_voice(self, voice_id: str) -> VoicePoolVoice | None: ...
